
export default {
    SIDEBAR_MOUNT: 'SIDEBAR_MOUNT',
    SIDEBAR_CLOSED: 'SIDEBAR_CLOSED',
    SIDEBAR_OPENED: 'SIDEBAR_OPENED',
    SIDEBAR_CHANGE: 'SIDEBAR_CHANGE',
    SIDEBAR_ANIMATING: 'SIDEBAR_ANIMATING',
    SIDEBAR_NAVIGATE_TO: 'SIDEBAR_NAVIGATE_TO',
};
